version: 0.2
batch:
  fast-fail: false

env:
  variables:
    JSON_SCHEMA_PATH: "scripts/jsonschema"

phases:
  install:
    runtime-versions:
      python: 3.10 
      nodejs: 16
    commands:
      - echo $CODEBUILD_SOURCE_VERSION
