version: 0.2
batch:
  fast-fail: false

env:
  variables:
    JSON_SCHEMA_PATH: "scripts/jsonschema"

phases:
  install:
    runtime-versions:
      python: 3.10 
      nodejs: 16
    commands:
      - curl -L https://github.com/github/hub/releases/download/v2.14.2/hub-linux-amd64-2.14.2.tgz -o hub.tgz
      - tar xvzf hub.tgz
      - sudo mv hub-linux-amd64-2.14.2/bin/hub /usr/local/bin/hub
      - hub version
      - ORG=$(echo $CODEBUILD_SOURCE_REPO_URL| cut -d'/' -f 4)
      - REPO=$(echo $CODEBUILD_SOURCE_REPO_URL| cut -d'/' -f 5)
      - echo "https://${ORG}:${GITHUB_TOKEN}@github.com/${ORG}/${REPO}"
      - git remote set-url origin https://${ORG}:${token}@github.com/${ORG}/${REPO}
      - git config --global user.email "andres.peralta@southworks.com"
      - git config --global user.name "AndresPeralta"
      - hub pull-request -b "main" -h "test1" -r "andres.peralta@southworks.com" -m "test"
