version: 0.2
batch:
  fast-fail: false

env:
  variables:
    JSON_SCHEMA_PATH: "scripts/jsonschema"

phases:
  install:
    runtime-versions:
      python: 3.10 
      nodejs: 16
    commands:
      - cd $CODEBUILD_SRC_DIR
      - echo $CODEBUILD_SOURCE_REPO_URL
      - git remote set-url origin https://AndresPeralta:${token}@github.com/AndresPeralta/test.git
      - git config --global user.email "andres.peralta@southworks.com"
      - git config --global user.name "AndresPeralta"
      - hub pull-request -b "main" -h "test1" -r "andres.peralta@southworks.com" -m "test"
